// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ArtistAnchorCover: typeof import('./src/components/ArtistAnchorCover.vue')['default']
    DiscCover: typeof import('./src/components/DiscCover.vue')['default']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    HeaderLine: typeof import('./src/components/HeaderLine.vue')['default']
    MusiclistRankingCover: typeof import('./src/components/MusiclistRankingCover.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SongsCover: typeof import('./src/components/SongsCover.vue')['default']
    TopRanking: typeof import('./src/components/TopRanking.vue')['default']
    WebFooter: typeof import('./src/components/WebFooter.vue')['default']
    WebHeader: typeof import('./src/components/WebHeader.vue')['default']
  }
}

export {}
