// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElInput: typeof import('element-plus/es')['ElInput']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WebFooter: typeof import('./src/components/webFooter/WebFooter.vue')['default']
    WebHeader: typeof import('./src/components/webHeader/WebHeader.vue')['default']
  }
}

export {}
